# Makefile

# Set Docker Compose project name to avoid image conflicts
DOCKER_COMPOSE=docker-compose -p ecsdemo_cluster

# Names of all supported workspaces (must not clash with any other target names)
WORKSPACES=dev prod prod2

include ../../includes/Terraform.mk
